# Generated by Django 3.0.3 on 2020-04-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200401_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivate',
            name='dob_private',
        ),
    ]
