# Generated by Django 3.0.3 on 2020-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200401_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_private',
            field=models.BooleanField(default=False, help_text='Designates if other users can view email address in profile', verbose_name='email private'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_private',
            field=models.BooleanField(default=False, help_text='Designates if other users can view first name in profile', verbose_name='first name private'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_private',
            field=models.BooleanField(default=False, help_text='Designates if other users can view last name in profile', verbose_name='last name private'),
        ),
    ]
