# Generated by Django 3.0.3 on 2020-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200401_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPrivate',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_private',
            field=models.BooleanField(default=False, verbose_name='email private'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name_private',
            field=models.BooleanField(default=True, verbose_name='first name private'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name_private',
            field=models.BooleanField(default=True, verbose_name='last name private'),
        ),
    ]
