# Generated by Django 3.0.3 on 2020-04-14 00:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200407_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(default='Describe your self and what your working on!bio'),
        ),
    ]
