# Generated by Django 3.0.3 on 2020-04-14 00:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(default='Describe your self and what your working on!'),
        ),
    ]
