# Generated by Django 3.0.3 on 2020-04-15 09:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200414_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=tinymce.models.HTMLField(default='Describe your self and what you are working on!'),
        ),
    ]
